version: "3.8"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - .:/app
    ports:
      - "8080:8080"
    environment: 
      - PORT=8080
      - HOST=0.0.0.0


