version: "3.8"
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - .:/app
    ports:
      - "9080:9080"
    environment: 
      - PORT=9080
      - HOST=0.0.0.0
